# Generated by Django 5.2.12 on 2026-04-05 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_workspaceinvite_refused_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('past_due', 'Past due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled')], default='trial', max_length=32)),
                ('plan_code', models.CharField(default='trial', max_length=64)),
                ('billing_interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('one_time', 'One time')], default='month', max_length=16)),
                ('currency', models.CharField(default='eur', max_length=8)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128)),
                ('stripe_subscription_item_ids', models.JSONField(blank=True, default=dict)),
                ('workspace_limit_base', models.PositiveIntegerField(default=1)),
                ('workspace_limit_addon', models.PositiveIntegerField(default=0)),
                ('seat_limit_base', models.PositiveIntegerField(default=5)),
                ('seat_limit_addon', models.PositiveIntegerField(default=0)),
                ('storage_quota_bytes_base', models.BigIntegerField(default=10737418240)),
                ('storage_quota_bytes_addon', models.BigIntegerField(default=0)),
                ('monthly_ai_tokens_base', models.PositiveBigIntegerField(default=100000)),
                ('ai_token_balance_topup', models.PositiveBigIntegerField(default=0)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('app_access_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner_user_id',),
            },
        ),
        migrations.CreateModel(
            name='BillingCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('subscription', 'Subscription'), ('payment', 'Payment')], max_length=24)),
                ('session_type', models.CharField(choices=[('subscription', 'Subscription'), ('ai_tokens', 'AI tokens')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='open', max_length=24)),
                ('stripe_session_id', models.CharField(max_length=128, unique=True)),
                ('checkout_url', models.URLField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='billing.billingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_checkout_sessions', to='workspaces.profile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_checkout_sessions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(max_length=128, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='eur', max_length=8)),
                ('subtotal_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('hosted_invoice_url', models.URLField(blank=True)),
                ('invoice_pdf_url', models.URLField(blank=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingaccount')),
            ],
            options={
                'ordering': ('-period_start', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BillingWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assignments', to='billing.billingaccount')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_assignment', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('workspace_id',),
            },
        ),
        migrations.CreateModel(
            name='BillingTokenLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('adjustment', 'Adjustment')], max_length=24)),
                ('tokens_delta', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField(default=0)),
                ('reference_kind', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_ledger_entries', to='billing.billingaccount')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_token_ledger_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['billing_account', 'created_at'], name='billing_bil_billing_f049fe_idx'), models.Index(fields=['reference_kind', 'reference_id'], name='billing_bil_referen_43e9fa_idx')],
            },
        ),
    ]
