# Generated by Django 5.2.12 on 2026-04-04 15:41

import django.db.models.deletion
import django.utils.timezone
import edilcloud.modules.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_profile_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=8)),
                ('display_language', models.CharField(blank=True, max_length=8)),
                ('is_translated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('unique_code', models.CharField(default=edilcloud.modules.projects.models.generate_content_code, max_length=32, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_post_comments', to='workspaces.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.postcomment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=edilcloud.modules.projects.models.comment_attachment_upload_to)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.postcomment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(-1, 'Draft'), (0, 'Closed'), (1, 'Active')], default=1)),
                ('logo', models.FileField(blank=True, upload_to=edilcloud.modules.projects.models.project_logo_upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='workspaces.profile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('to-do', 'To do'), ('progress', 'Progress'), ('completed', 'Completed')], default='to-do', max_length=16)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('alert', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('workers', models.ManyToManyField(blank=True, related_name='project_activities', to='workspaces.profile')),
            ],
            options={
                'ordering': ('datetime_start', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('is_public', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'ordering': ('path', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(upload_to=edilcloud.modules.projects.models.project_document_upload_to)),
                ('is_public', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.projectfolder')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('unique_code', models.CharField(blank=True, max_length=9, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Refused')], default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_project_invite_codes', to='workspaces.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('o', 'Owner'), ('d', 'Delegate'), ('m', 'Manager'), ('w', 'Worker')], default='w', max_length=1)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Refused')], default=1)),
                ('disabled', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
                ('project_invitation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='workspaces.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'ordering': ('project_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.FileField(upload_to=edilcloud.modules.projects.models.project_photo_upload_to)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_kind', models.CharField(choices=[('work-progress', 'Work progress'), ('issue', 'Issue'), ('documentation', 'Documentation')], default='work-progress', max_length=32)),
                ('text', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=8)),
                ('display_language', models.CharField(blank=True, max_length=8)),
                ('is_translated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('unique_code', models.CharField(default=edilcloud.modules.projects.models.generate_content_code, max_length=32, unique=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.projectactivity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_posts', to='workspaces.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.project')),
            ],
            options={
                'ordering': ('-published_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectpost'),
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=edilcloud.modules.projects.models.post_attachment_upload_to)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projectpost')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('share_status', models.BooleanField(default=False)),
                ('shared_task', models.PositiveIntegerField(blank=True, null=True)),
                ('only_read', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('assigned_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to='workspaces.workspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ('date_start', 'id'),
            },
        ),
        migrations.AddField(
            model_name='projectpost',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.projecttask'),
        ),
        migrations.AddConstraint(
            model_name='projectfolder',
            constraint=models.UniqueConstraint(fields=('project', 'path'), name='unique_project_folder_path'),
        ),
        migrations.AddIndex(
            model_name='projectinvitecode',
            index=models.Index(fields=['project', 'email'], name='projects_pr_project_745253_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_3f16c8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['profile', 'status'], name='projects_pr_profile_f1ac9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'profile'), name='unique_project_profile'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', 'created_at'], name='projects_po_post_id_514cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'date_start'], name='projects_pr_project_f41dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpost',
            index=models.Index(fields=['task', 'published_date'], name='projects_pr_task_id_fa9120_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpost',
            index=models.Index(fields=['activity', 'published_date'], name='projects_pr_activit_c4d183_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpost',
            index=models.Index(fields=['project', 'alert'], name='projects_pr_project_eabb27_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['task', 'datetime_start'], name='projects_pr_task_id_15472f_idx'),
        ),
    ]
