# Generated by Django 5.2.12 on 2026-04-05 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspaceinvite_refused_at"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPostSeenState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_states",
                        to="projects.projectpost",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_project_posts",
                        to="workspaces.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-seen_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="projectpostseenstate",
            constraint=models.UniqueConstraint(
                fields=("post", "profile"),
                name="unique_project_post_seen_state",
            ),
        ),
        migrations.AddIndex(
            model_name="projectpostseenstate",
            index=models.Index(fields=["profile", "seen_at"], name="projects_pr_profile_d0de4f_idx"),
        ),
        migrations.AddIndex(
            model_name="projectpostseenstate",
            index=models.Index(fields=["post", "seen_at"], name="projects_pr_post_id_639955_idx"),
        ),
    ]
