# Generated by Django 5.2.12 on 2026-04-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectactivity_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScheduleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('e2s', 'Finish to start'), ('s2s', 'Start to start'), ('e2e', 'Finish to finish'), ('s2e', 'Start to finish')], default='e2s', max_length=3)),
                ('lag_days', models.SmallIntegerField(default=0)),
                ('origin', models.CharField(default='manual', max_length=32)),
            ],
            options={
                'ordering': ('project_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='projectschedulelink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_links', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectschedulelink',
            name='source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_schedule_links', to='projects.projectactivity'),
        ),
        migrations.AddField(
            model_name='projectschedulelink',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_schedule_links', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectschedulelink',
            name='target_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_schedule_links', to='projects.projectactivity'),
        ),
        migrations.AddField(
            model_name='projectschedulelink',
            name='target_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_schedule_links', to='projects.projecttask'),
        ),
        migrations.AddIndex(
            model_name='projectschedulelink',
            index=models.Index(fields=['project', 'source_task'], name='projects_pr_project_6b506f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschedulelink',
            index=models.Index(fields=['project', 'source_activity'], name='projects_pr_project_f0cc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschedulelink',
            index=models.Index(fields=['project', 'target_task'], name='projects_pr_project_43984e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschedulelink',
            index=models.Index(fields=['project', 'target_activity'], name='projects_pr_project_314b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschedulelink',
            index=models.Index(fields=['project', 'link_type'], name='projects_pr_project_d15ce5_idx'),
        ),
    ]
