# Generated by Django 5.2.12 on 2026-04-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectmember_role_codes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectcompanycolor',
            new_name='projects_pr_project_71a6e6_idx',
            old_name='projects_pro_project_540f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectoperationalevent',
            new_name='projects_pr_project_361598_idx',
            old_name='projects_pr_project_459db1_idx',
        ),
        migrations.RenameIndex(
            model_name='projectoperationalevent',
            new_name='projects_pr_project_f2049b_idx',
            old_name='projects_pr_project_645090_idx',
        ),
        migrations.RenameIndex(
            model_name='projectoperationalevent',
            new_name='projects_pr_project_6b2162_idx',
            old_name='projects_pr_project_53c056_idx',
        ),
        migrations.RenameIndex(
            model_name='projectoperationalevent',
            new_name='projects_pr_project_f8400f_idx',
            old_name='projects_pr_project_1f1480_idx',
        ),
    ]
