# Generated by Django 5.2.12 on 2026-04-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectposttranslation_and_commenttranslation'),
        ('workspaces', '0003_workspaceinvite_refused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_snapshot_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='is_demo_master',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemoProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('business_date', models.DateField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('seed_hash', models.CharField(blank=True, max_length=64)),
                ('asset_manifest_hash', models.CharField(blank=True, max_length=64)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('invalid', 'Invalid')], default='draft', max_length=16)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('active_in_production', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('export_relative_path', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demo_project_snapshots', to='workspaces.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['project', 'active_in_production'], name='projects_de_project_dfc170_idx'), models.Index(fields=['project', 'validation_status'], name='projects_de_project_56a31f_idx'), models.Index(fields=['version'], name='projects_de_version_62cef3_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_demo_project_snapshot_name_version')],
            },
        ),
    ]
