# Generated by Django 5.2.12 on 2026-04-04 22:35

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0002_profile_phone_verified_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(blank=True, max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("sender_company_name", models.CharField(blank=True, max_length=255)),
                ("sender_position", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("project_id", models.PositiveIntegerField(blank=True, null=True)),
                ("task_id", models.PositiveIntegerField(blank=True, null=True)),
                ("activity_id", models.PositiveIntegerField(blank=True, null=True)),
                ("post_id", models.PositiveIntegerField(blank=True, null=True)),
                ("comment_id", models.PositiveIntegerField(blank=True, null=True)),
                ("folder_id", models.PositiveIntegerField(blank=True, null=True)),
                ("document_id", models.PositiveIntegerField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workspaces.profile",
                    ),
                ),
                (
                    "sender_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_notifications",
                        to="workspaces.profile",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient_profile", "read_at"], name="notificatio_recipie_c3efa6_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient_profile", "created_at"], name="notificatio_recipie_d36712_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["kind"], name="notificatio_kind_b1972d_idx"),
        ),
    ]
