# Generated by Django 5.2.12 on 2026-04-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_584bd6_idx',
            old_name='notificatio_recipie_c3efa6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_482887_idx',
            old_name='notificatio_recipie_d36712_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_kind_e87f17_idx',
            old_name='notificatio_kind_b1972d_idx',
        ),
    ]
