# Generated by Codex on 2026-04-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_rename_notificatio_recipie_c3efa6_idx_notificatio_recipie_584bd6_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=512, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("installation_id", models.CharField(blank=True, max_length=128)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("app_version", models.CharField(blank=True, max_length=64)),
                ("push_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_registered_at", models.DateTimeField(blank=True, null=True)),
                ("last_push_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_push_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_push_error", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_devices",
                        to="workspaces.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="notificationdevice",
            index=models.Index(fields=["profile", "is_active"], name="notificatio_profile_95f1cb_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdevice",
            index=models.Index(fields=["user", "is_active"], name="notificatio_user_id_17b374_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdevice",
            index=models.Index(fields=["installation_id"], name="notificatio_install_7b89bc_idx"),
        ),
    ]
