# Generated by Codex on 2026-04-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPushDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("invalid_token", "Invalid token"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="notifications.notificationdevice",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_attempt_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="notificationpushdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "device"),
                name="notifications_push_delivery_unique_notification_device",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpushdelivery",
            index=models.Index(fields=["notification", "status"], name="notificatio_notific_f675cf_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpushdelivery",
            index=models.Index(fields=["device", "status"], name="notificatio_device__6b6b71_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpushdelivery",
            index=models.Index(fields=["last_attempt_at"], name="notificatio_last_at_52f447_idx"),
        ),
    ]
