# Generated by Django 5.2.12 on 2026-04-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpushdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdevice',
            new_name='notificatio_profile_af392c_idx',
            old_name='notificatio_profile_95f1cb_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdevice',
            new_name='notificatio_user_id_89ef0a_idx',
            old_name='notificatio_user_id_17b374_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdevice',
            new_name='notificatio_install_f22714_idx',
            old_name='notificatio_install_7b89bc_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpushdelivery',
            new_name='notificatio_notific_ae60a7_idx',
            old_name='notificatio_notific_f675cf_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpushdelivery',
            new_name='notificatio_device__2e39bc_idx',
            old_name='notificatio_device__6b6b71_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpushdelivery',
            new_name='notificatio_last_at_f1d272_idx',
            old_name='notificatio_last_at_52f447_idx',
        ),
    ]
