# Generated by Django 5.2.12 on 2026-04-04 13:46

import django.db.models.deletion
import edilcloud.modules.workspaces.models
from django.conf import settings
from django.db import migrations, models
import secrets


def generate_invite_code() -> str:
    return f"{secrets.randbelow(10000):04d}-{secrets.randbelow(10000):04d}"


def populate_invite_codes(apps, _schema_editor):
    workspace_invite_model = apps.get_model("workspaces", "WorkspaceInvite")
    existing_codes = set(
        workspace_invite_model.objects.exclude(invite_code="").values_list("invite_code", flat=True)
    )
    for invite in workspace_invite_model.objects.filter(invite_code="").iterator():
        candidate = generate_invite_code()
        while candidate in existing_codes:
            candidate = generate_invite_code()
        invite.invite_code = candidate
        invite.save(update_fields=["invite_code"])
        existing_codes.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.CreateModel(
            name='WorkspaceAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(default='it', max_length=8)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('photo_path', models.CharField(blank=True, max_length=512)),
                ('picture_url', models.URLField(blank=True)),
                ('request_token', models.CharField(default=edilcloud.modules.workspaces.models.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refused_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workspace_access_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['workspace', 'status'], name='workspaces__workspa_005049_idx'), models.Index(fields=['email', 'status'], name='workspaces__email_4ce66a_idx')],
            },
        ),
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='invite_code',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
