# Generated by Django 5.2.12 on 2026-04-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectassistantmessage',
            new_name='assistant_p_project_8ac71c_idx',
            old_name='assistant_m_project_4e2e6b_idx',
        ),
        migrations.RenameIndex(
            model_name='projectassistantmessage',
            new_name='assistant_p_project_9665bb_idx',
            old_name='assistant_m_project_58799b_idx',
        ),
    ]
