# Generated by Django 5.2.12 on 2026-04-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_rename_assistant_m_project_4e2e6b_idx_assistant_p_project_8ac71c_idx_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssistantSourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('drafting', 'Drafting')], default='project', max_length=32)),
                ('source_key', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('custom_id', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('remote_text_document_id', models.CharField(blank=True, max_length=128)),
                ('remote_file_document_id', models.CharField(blank=True, max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('assistant_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_states', to='assistant.projectassistantstate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_source_states', to='projects.project')),
            ],
            options={
                'ordering': ('assistant_state_id', 'scope', 'source_key'),
                'indexes': [models.Index(fields=['assistant_state', 'scope'], name='assistant_p_assista_c36595_idx'), models.Index(fields=['project', 'scope', 'source_type'], name='assistant_p_project_5e718a_idx')],
                'constraints': [models.UniqueConstraint(fields=('assistant_state', 'scope', 'source_key'), name='unique_assistant_source_scope_key')],
            },
        ),
    ]
