# Generated by Django 5.2.12 on 2026-04-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_projectassistantsourcestate"),
        ("workspaces", "0003_workspaceinvite_refused_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAssistantThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_threads",
                        to="workspaces.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_threads",
                        to="projects.project",
                    ),
                ),
            ],
            options={"ordering": ("-last_message_at", "-updated_at", "-id")},
        ),
        migrations.AddField(
            model_name="projectassistantmessage",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="assistant.projectassistantthread",
            ),
        ),
        migrations.AddIndex(
            model_name="projectassistantthread",
            index=models.Index(
                fields=["project", "archived_at", "last_message_at"],
                name="assistant_p_project_f257f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectassistantthread",
            index=models.Index(fields=["project", "created_at"], name="assistant_p_project_aeed2b_idx"),
        ),
        migrations.AddIndex(
            model_name="projectassistantmessage",
            index=models.Index(fields=["thread", "created_at"], name="assistant_p_thread__299dbf_idx"),
        ),
    ]
