# Generated by Django 5.2.12 on 2026-05-06 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_upgrade_assistant_embeddings_to_large'),
        ('projects', '0017_projectdrawingpin_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssistantWikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('overview', 'Overview'), ('timeline', 'Timeline'), ('open_issues', 'Open issues'), ('decisions', 'Decisions'), ('risks', 'Risks'), ('documents', 'Documents'), ('companies', 'Companies'), ('people', 'People'), ('tasks', 'Tasks'), ('activities', 'Activities')], default='overview', max_length=32)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('body_markdown', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('generated_version', models.BigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_wiki_pages', to='projects.project')),
            ],
            options={
                'ordering': ('project_id', 'slug'),
                'indexes': [models.Index(fields=['project', 'page_type'], name='assistant_p_project_238b73_idx'), models.Index(fields=['project', 'is_stale', 'generated_at'], name='assistant_p_project_b3a48e_idx'), models.Index(fields=['project', 'schema_version'], name='assistant_p_project_38737f_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'slug'), name='unique_project_assistant_wiki_slug')],
            },
        ),
    ]
