# Generated by Django 5.2.12 on 2026-05-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_projectassistantwikipage'),
        ('projects', '0017_projectdrawingpin_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssistantGraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('summary_markdown', models.TextField(blank=True)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('generated_version', models.BigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_graph_snapshot', to='projects.project')),
            ],
            options={
                'ordering': ('project_id',),
                'indexes': [models.Index(fields=['project', 'is_stale', 'generated_at'], name='assistant_p_project_069120_idx'), models.Index(fields=['project', 'schema_version'], name='assistant_p_project_ff82bb_idx')],
            },
        ),
    ]
